export const arms = [
  "Barbell Triceps Overhead Extension",
  "Assisted Dip",
  "Barbell Skullcrusher",
  "Cable Overhead Triceps Extension",
  "Cable Single Arm Pushdown",
  "Cable Triceps Pushdown",
  "Dip",
  "Dumbbell Skullcrusher",
  "EZ Bar Overhead Triceps Extension",
  "Inverted Skullcrusher",
  "Machine Triceps Extension",
  "Machine Triceps Pushdown",
  "Rope Overhead Triceps Extension",
  "Rope Pushdown",
  "Seated EZ Bar Overhead Triceps Extension",
  "JM Press",
  "Seated Barbell Overhead Triceps Extension",

  "Alternating Dumbbell Curl",
  "Barbell Curl Narrow Grip",
  "Barbell Curl Normal Grip",
  "Cable EZ Bar Curl Wide Grip",
  "Cable EZ Bar Curl",
  "Dumbbell Single Arm Preacher Curl",
  "Dumbbell Spider Curl",
  "Dumbbell Twist Curl",
  "EZ Bar Curl Narrow Grip",
  "EZ Bar Curl Wide Grip",
  "EZ Bar Preacher Curl",
  "EZ Bar Spider Curl",
  "Hammer Curl",
  "Incline Dumbbell Curl",
  "Machine Preacher Curl",
  "Rope Twist Curl"
]