export const back = [
  "Barbell Bent Over Row",
  "Cambered Bar Row",
  "Barbell Row to Chest",
  "Underhand EZ Bar Row",
  "Smith Machine Row",
  "Chest Supported Row",
  "Machine Chest Supported Row",
  "T Bar Row",
  "Incline Dumbbell Row",
  "Two Arm Dumbbell Row",
  "Single Arm Dumbbell Row",
  "Hammer Low Row",
  "Inverted Row",
  "Seal Row",
  "Seated Cable Row",
  "Normal Grip Pullup",
  "Wide Grip Pullup",
  "Parallel Grip Pullup",
  "Underhand Pullup",
  "Assisted Normal Grip Pullup",
  "Assisted Wide Grip Pullup",
  "Assisted Parallel Pullup",
  "Assisted Underhand Pullup",
  "Normal Grip Pulldown",
  "Wide Grip Pulldown",
  "Parallel Pulldown",
  "Underhand Pulldown",
  "Narrow Grip Pulldown",
  "Hammer High Row",
  "Dumbbell Pullover",
  "Machine Pullover",
  "Straight Arm Pulldown"
]