export const chest = [
  "Bench press",
  "Dumbbell Fly",
  "Incline bench press",
  "Machine press",
  "Cable bench press",
  "Cable Fly",
  "Cable Bent Fly",
  "Cable Underhand Fly",
  "Cambered Bar Bench Press",
  "Deficit Pushup",
  "Flat Dumbbell Bench Press",
  "Flat Dumbbell Fly",
  "Flat Dumbbell Press/Fly",
  "Flat Hammer Machine Press",
  "Hammer Machine Press",
  "High Incline Dumbbell Press",
  "Incline Dumbbell Fly",
  "Incline Dumbbell Press",
  "Incline Dumbbell Press/Fly",
  "Incline Machine Chest Press",
  "Incline Barbell Press Medium Grip",
  "Incline Barbell Press Narrow Grip",
  "Incline Barbell Press Wide Grip",
  "Low Incline Dumbbell Press",
  "Machine Chest Press",
  "Machine Fly",
  "Medium Grip Bench Press",
  "Narrow Pushup",
  "Narrow Grip Bench Press",
  "Pec Deck Fly",
  "Pushup",
  "Smith Machine Bench Press",
  "Smith Machine Incline Press",
  "Smith Machine Narrow Grip Press",
  "Smith Machine Narrow Grip Incline Press",
  "Smith Machine Wide Grip Press",
  "Smith Machine Wide Grip Incline Press",
  "Wide Grip Bench Press"
]